{
 "title": "default",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Clock", "type": "grafana-clock-panel", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Key Strokes / m",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(total_words_count_counter[1m])"
    }
   ]
  },
  {
   "title": "草",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "increase(total_words_count_counter[1h])"
    }
   ]
  },
  {
   "title": "Ave. Key Strokes / d",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "avg_over_time(total_words_count_counter[1d])"
    }
   ]
  },
  {
   "title": "Key Strokes / d",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "increase(total_words_count_counter[1d])"
    }
   ]
  }
 ]
}