groups:
- name: alert.rules
  rules:
  - alert: probe_down
    expr: probe_success == 0
    for: 5m
    labels:
      level: emergency
      expr: probe_success == 0
    annotations:
      value: '{{ $value }}'
      summary: "Instance {{ $labels.instance }} down"
      description: "[{{ $labels.job }}][{{ $labels.instance }}] down for more than 5m"
- name: node
  rules:
  - alert: GPU_too_hot
    expr: "dcgm_gpu_temp > 85"
    for: 5m
    labels:
      level: emergency
    annotations:
      value: '{{ $value }}'
      summary: "Instance {{ $labels.instance }} down"
      description: "[{{ $labels.job }}][{{ $labels.instance }}] too hot"
