global:
  scrape_interval: 5s
  external_labels:
    monitor: codelab-monitor

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - 172.30.0.2:9090
        - 172.30.0.3:9100

